Hands 3d Motion Viewer
======================

A tool to view the 3d motion data generated by the tracker of the project **"3D Object Reconstruction from
Hand-Object Interactions"**. The datasets can be obtained freely in the project page http://files.is.tue.mpg.de/dtzionas/In-Hand-Scanning/

Dependencies
----

OpenCV, Eigen3, OpenGL and QT 4 and CMake

Build
----

    mkdir build
    cd build
    cmake ..
    make

Run
----

    cd bin
    ./3d_viewer
    
In the gui window, click in the "load sequence" button and select one of the following sequences:

- 01 - Water bottle
- 02 - Bowling pin
- 03 - Small bottle
- 04 - Sphere

Then you can load the background images by clicking in the "find path" button and selecting the folder of the dataset. For example, for dataset 03 you will have to select the root folder that has the folder "1" under it.

    |-03 <-- folder to choose
      |- 1 
         |- depth
         |- depth_png
         |- depth_viz
         |- joints_2D_GT
         |- rgb
         |- rgbd


         

